const fs = require("fs");
const path = require("path");

const outputFile = path.join(__dirname, "pages.js");
const start = 3;
const end = 606;

let content = `// Auto-generated Quran pages mapping
// Generated by generatePages.js

export const pages = {\n`;

for (let i = start; i <= end; i++) {
  const num = String(i).padStart(3, "0");
  content += `  ${i}: require('./assets/quran_pages/page_${num}.webp'),\n`;
}

content += `};\n`;

fs.writeFileSync(outputFile, content, "utf8");
console.log(`✅ pages.js generated with entries from ${start} to ${end}`);
